version: "3.8"
services:
  postgres:
    build:
      context: docker-compose/postgres
      dockerfile: Postgres.Dockerfile
    container_name: postres-db
    environment:
      POSTGRES_PASSWORD: password
  file-management:
    build: .
    container_name: file-management
    ports:
      - 8080:8080
    environment:
      DB_HOST: postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: local-storage
#      SPRING_PROFILES_ACTIVE: local-storage, s3-storage
#      S3_ACCESS_KEY_ID:
#      S3_ACCESS_KEY_SECRET:
#      S3_BUCKET_REGION:
#      S3_BUCKET: