server:
  servlet:
    context-path: /file-management-service
spring:
  profiles:
    active: local-storage, s3-storage
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/postgres?currentSchema=file_management
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/changelog/changelog-master.xml
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
file-management:
  storages:
    LOCAL:
      - bucket: ${user.home}/demo-bucket
    S3:
      - bucket: ${S3_BUCKET}
        options:
          ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
          ACCESS_KEY_SECRET: ${S3_ACCESS_KEY_SECRET}
          BUCKET_REGION: ${S3_BUCKET_REGION}
